language: java
after_success:
  - mvn clean test jacoco:report coveralls:report
jdk:
  - oraclejdk8
env:
  global:
     - secure: "ahXdaQ/9v55uziqoUDqGaXLg412tNQ0vLu7hTPie+IbtuKN7PZx0NtCJ6QoN3D9WqoqLgIOtvgdvCRNYOwoEZmVkgTRm/kkTeW1gxm1aPeRkd448zTxke1AKzs+p3p+qK7bxBwwc/+EI1isFFg6mHj+ngucFuNEez6ps2sneltfBJG4CEk8MZ/JLG3a8AloRSS/moHPfEdA89J+51l5VeeWkgwTkToEjkHFbCyfnCBfwWbm+THvlTZ04KjY+WGHXZC9y+oHIgo6KrG32NJwY/iy3xKrJP15aeyYTkH6qPeAA5kDub5aB6fMbgYZrEz7lBhYzfejBwbNZDBjaCyQ1wUQETukeKafJYToor5EY2GG7G8+9rTv4qi2D7xs+EaztMKa9tM9oeyZROybMzgADeXWEjnPV8htny5c5YRw0Swp9f9XAFiB9rogri4PNIKN1+R9CXPsPCLTP36lCpbA/3aJ6Y/MEjFwtUnArjOQWSrZOPU9dTD1kC7/KFwcGw3TqX7RT6wCYvB9v4DcmblprR0ijyFbB9zOechQBTbMkCCuLnyTKKblHokfoIjs9o1bxwviz+5ZqXuX6DJOPTV4E43+1pxmZTP81O/ciALzccssFcI1mRBQMMnsW0hdQ5AC38/vvf7iBfLNR+C0yO177hCRZFpDZ2TbdVezN8pChFxM="